[theme]
base = "light"
primaryColor = "#087F8C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F8FA"
textColor = "#172033"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
